# Base16 colors for configurations
# Colors must be without hash, as some configs require it, some don't

term_font = "Iosevka Term SS14"
system_font = "Fira Sans"

# Skeletor
# accent = "95d34c"
# base00 = "111122"
# base01 = "291b36"
# base02 = "313148"
# base03 = "746e9f"
# base04 = "8e7e9d"
# base05 = "d6cdee"
# base06 = "eeeeff"
# base07 = "ffffff"
# base08 = "ff7979"
# base09 = "d8d4ab"
# base0A = "f3ae7c"
# base0B = "95d34c"
# base0C = "f7a7ca"
# base0D = "7eb1f7"
# base0E = "a886ef"
# base0F = "4455bb"

# Gruvbox (dark, medium)
accent = "fe8019"
base00 = "282828"
base01 = "3c3836"
base02 = "504945"
base03 = "665c54"
base04 = "bdae93"
base05 = "d5c4a1"
base06 = "ebdbb2"
base07 = "fbf1c7"
base08 = "fb4934"
base09 = "fe8019"
base0A = "fabd2f"
base0B = "b8bb26"
base0C = "8ec07c"
base0D = "83a598"
base0E = "d3869b"
base0F = "d65d0e"
