# Base16 colors for configurations
# Colors must be without hash, as some configs require it, some don't

term_font = "Iosevka Term SS14"
system_font = "Fira Sans"

# TODO: Experimental, don't change yet - only works with some values in tint2
base_dpi = 96
scale = 1

# Skeletor
accent = "95d34c"
base00 = "111122"
base01 = "291b36"
base02 = "313148"
base03 = "746e9f"
base04 = "8e7e9d"
base05 = "d6cdee"
base06 = "eeeeff"
base07 = "ffffff"
base08 = "ff7979"
base09 = "d8d4ab"
base0A = "f3ae7c"
base0B = "95d34c"
base0C = "f7a7ca"
base0D = "7eb1f7"
base0E = "a886ef"
base0F = "4455bb"

# Gruvbox (dark, medium)
# accent = "fe8019"
# base00 = "282828"
# base01 = "3c3836"
# base02 = "504945"
# base03 = "665c54"
# base04 = "bdae93"
# base05 = "d5c4a1"
# base06 = "ebdbb2"
# base07 = "fbf1c7"
# base08 = "fb4934"
# base09 = "fe8019"
# base0A = "fabd2f"
# base0B = "b8bb26"
# base0C = "8ec07c"
# base0D = "83a598"
# base0E = "d3869b"
# base0F = "d65d0e"

# Monokai
# accent = "a6e22e"
# base00 = "272822"
# base01 = "383830"
# base02 = "49483e"
# base03 = "75715e"
# base04 = "a59f85"
# base05 = "f8f8f2"
# base06 = "f5f4f1"
# base07 = "f9f8f5"
# base08 = "f92672"
# base09 = "fd971f"
# base0A = "f4bf75"
# base0B = "a6e22e"
# base0C = "a1efe4"
# base0D = "66d9ef"
# base0E = "ae81ff"
# base0F = "cc6633"

# Nord
# accent = "b48ead"
# base00 = "2e3440"
# base01 = "3b4252"
# base02 = "434c5e"
# base03 = "4c566a"
# base04 = "d8dee9"
# base05 = "e5e9f0"
# base06 = "eceff4"
# base07 = "8fbcbb"
# base08 = "88c0d0"
# base09 = "81a1c1"
# base0A = "5e81ac"
# base0B = "bf616a"
# base0C = "d08770"
# base0D = "ebcb8b"
# base0E = "a3be8c"
# base0F = "b48ead"