# Base16 colors for configurations
base00 = "#111122"
base01 = "#291b36"
base02 = "#313148"
base03 = "#746e9f"
base04 = "#8e7e9d"
base05 = "#d6cdee"
base06 = "#eeeeff"
base07 = "#ffffff"
base08 = "#ff7979"
base09 = "#d8d4ab"
base0A = "#f3ae7c"
base0B = "#95d34c"
base0C = "#f7a7ca"
base0D = "#7eb1f7"
base0E = "#a886ef"
base0F = "#4455bb"